### ISSUE TITLE
feat: config

### ISSUE THREAD

**Issue by DmACKGL** [DerYeger/pnpm-setup-action#2]
### Affected Packages

- [ ] @yeger/eslint-config
- [ ] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

It would be great to have a method for defining a configuration (`config set` commands) or a way to append commands after installing PNPM but before executing `pnpm install`.

This feature would be useful for setting up a registry, among other things.

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Is there any reason a `.npmrc` can't be present in the repo?
